### ISSUE TITLE
Problem with convert :

### ISSUE THREAD

**Issue by belidi** [xentux/weewx_meteohub_converter#1]
I can not convert the "raw" file here are the errors I get:
: ./wm_convert.py -i / home / pi / Documents / 201601 / raw -o 201601.csv

result: Traceback (most recent call last):
   File "./wm_convert.py", line 10, in <module>
     from weewx_meteohub.importer import Import
   File "/tmp/weewx_meteohub_converter-main/weewx_meteohub/importer.py", line 144
     print (f "First interval: {interval_start} - {interval_end}")
                                                              ^
SyntaxError: invalid syntax

**Comment by xentux** [comment]
Sorry for the really veeeery long time for this reply.
I can't reproduce this issue.
Please, pull the current version of this repository and use poetry to create a virtual environment with all required modules.
If this issue is still relevant for you, please give me a hint.
